repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: npm run lint
        entry: npm run --silent lint
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx)$
      - id: prettier
        name: prettier (format)
        entry: npm run --silent lint:fix
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx|json|md)$
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.7.2
    hooks:
      - id: golangci-lint
